name: Build iOS App

on:
  push:
    branches:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.3'

      - name: Install dependencies
        run: flutter pub get

      - name: Build iOS
        run: flutter build ios --no-codesign

      - name: collect ipa artifacts
        uses: actions/upload-artifact@v2
        with:
         name: adhoc-ipa
         # Path to the release files
         path: build/ios/ipa/*.ipa

