name: Build and Upload IPA

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.3'

      - name: Install xcoder
        run: |
          gem install xcoder

      - name: Install dependencies
        run: flutter pub get

      - name: Build iOS Release
        run: flutter build ios --release --no-codesign

      - name: Archive Runner.app
        run: xcode-project archive --workspace ios/Runner.xcworkspace --scheme Runner --archive-path build/ios/Runner.xcarchive

      - name: Build IPA
        run: xcode-project build-ipa --archive-path build/ios/Runner.xcarchive --export-path build/ios/ipa

      - name: Collect IPA artifact
        uses: actions/upload-artifact@v2
        with:
          name: adhoc-ipa
          path: build/ios/ipa/*.ipa
