name: IOSBuilder

on: [workflow_dispatch]

jobs:
  build:
    runs-on: macos-latest

    env:
      FLUTTER_HOME: /Users/runner/hostedtoolcache/flutter/1.17.5-stable/arm64

    steps:
      - uses: actions/checkout@v1

      - name: Create Folder for certificates and profiles
        run: |
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          mkdir -p ~/Library/MobileDevice/Certificates/
       
      - name: Get Certificate
        run: |
          echo "${{ secrets.P12_BASE64 }}" | base64 --decode > ~/Library/MobileDevice/Certificates/certificate.p12
          ls -l ~/Library/MobileDevice/Certificates/
          file ~/Library/MobileDevice/Certificates/certificate.p12
       
      - name: Get Profile
        run: |
          echo "${{ secrets.MOBILEPROVISION_BASE64 }}" | base64 --decode > ~/Library/MobileDevice/Provisioning\ Profiles/decoded.mobileprovision

      - name: Install python and codemagic tools
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install python dependencies
        run: python -m pip install codemagic-cli-tools

      - name: Debug Secrets (Do not output sensitive information)
        run: |
          echo "Debugging Secrets"
          echo "P12_BASE64 length: ${#P12_BASE64}"
          echo "MOBILEPROVISION_BASE64 length: ${#MOBILEPROVISION_BASE64}"
          echo "cert_password length: ${#cert_password}"

      - name: Install Flutter
        uses: subosito/flutter-action@v1.3.2
        with:
          flutter-version: '1.17.5'
      
      - name: Flutter Environment Setup
        run: |
          echo "FLUTTER_HOME=${FLUTTER_HOME}" >> $GITHUB_ENV
          echo "${FLUTTER_HOME}/bin" >> $GITHUB_PATH
          echo "${FLUTTER_HOME}/bin/cache/dart-sdk/bin" >> $GITHUB_PATH
      
      - run: flutter pub get

      - name: Building IPA
        run: |
          xcode-project use-profiles
          flutter build ios --release --no-codesign
          xcode-project build-ipa --workspace ios/Runner.xcworkspace --scheme Runner --config Release

      - name: Collect ipa artifacts
        uses: actions/upload-artifact@v2
        with:
          name: adhoc-ipa
          path: build/ios/ipa/*.ipa
